#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
apt-install -y debconf-utils
wget https://raw.githubusercontent.com/passwordlandia/ldap/master/ldap_debconf

while read line; do echo "$line" | debconf-set-selection; < ldap_debconf

apt-get -y install libpam-ldap nscd

sed -i 's/compat/compat ldap/g' /etc/nsswitch.conf

/etc/init.d/nscd restart

apt-get install nfs-client -y

showmount -e 10.142.0.14
mkdir /mnt/test
echo "10.142.0.14:/var/nfsshare/testing        /mnt/test       nfs     defaults 0 0" >> /etc/fstab

mount -a
