#!/bin/bash

sudo yum install -y epel-release
sudo yum install -y python-pip python-devel gcc postgresql-server postgresql-devel postgresql-contrib

sudo postgresql-setup initdb
sudo systemctl enable postgresql
sudo systemctl start postgresql

cp /var/lib/pgsql/data/pg_hba.conf /var/lib/pgsql/data/pg_hba.conf.bak

sed -i 's/ident/md5/g' /var/lib/pgsql/data/pg_hba.conf

sudo systemctl restart postgresql
sudo systemctl enable postgresql

sudo yum install -y wget

wget https://raw.githubusercontent.com/passwordlandia/ldap/master/sqlfile.sql

sudo -i -u postgres psql -U postgres -f /sqlfile.sql

###You are done. If you want to test this environment, SSH into the server and type 
###sudo systemctl status postgresql####
