#!/bin/bash
yum -y install pip
yum -y install python-pip
yum install -y pip install virtualenv
yum -y pip install --upgrade pip

mkdir /opt/myproject
cd /opt/myproject/

pip install virtualenv
virtualenv myprojectenv
source myprojectenv/bin/activate

pip install django psycopg2
django-admin.py startproject myproject .

yum -y install tree

cd myproject/



cd ~/myproject

python manage.py makemigrations
python manage.py migrate

source myprojectenv/bin/activate

python manage.py createsuperuser

python manage.py runserver 0.0.0.0:8000

http://server_domain_or_IP:8000
