#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
apt-get -y install libpam-ldap nscd
wget https://raw.githubusercontent.com/passwordlandia/ldap/master/ldap_debconf

while read line; do echo "$line" | debconf-set-selection; done < ldap_debconf

apt-get -y install libpam-ldap nscd

sed -i 's/compat/compat ldap/g' /etc/nsswitch.conf

sed -i 's/PasswordAuthentication no/PasswordAuthentication Yes/g' /etc/ssh/sshd_config

/etc/init.d/nscd restart

export DEBIAN_FRONTEND=interactive

sed -i 's,uri ldapi:///,uri ldap://10.142.0.14,g' /etc/ldap.conf
sed -i 's/base dc=example,dc=net/base dc=nti310,dc=local/g' /etc/ldap.conf

apt-get install nfs-client -y

showmount -e 10.142.0.14

mkdir /mnt/test

echo "10.142.0.14:/var/nfsshare/testing        /mnt/test       nfs     defaults 0 0" >> /etc/fstab
