#!/bin/bash
yum install git
cd tmp
yum -y install openldap-servers
yum -y install openldap-clients
cp /usr/share/openldap-servers/DB_CONFIG.example /var/lib/ldap/DB_CONFIG
chown ldap. /var/lib/ldap/DB_CONFIG
systemctl enable slapd
systemctl start slapd
yum -y install httpd
yum -y install epel-release
yum -y install phpldapadmin
setsebool -P httpd_can_connect_ldap on
systemctl enable httpd
systemctl start httpd
