#!/bin/bash

yum install epel-release -y
yum update -y
yum install python-pip -y
sudo pip install --upgrade pip
yum install nginx -y

yum install python34-devel gcc -y
curl -O https://bootstrap.pypa.io/get-pip.py
/usr/bin/python3.4 get-pip.py

pip install virtualenv
mkdir -p /var/www && cd /var/www
virtualenv -p python3 p3venv

source p3venv/bin/activate
pip install uwsgi
pip install django

echo -e "upstream django {
	server unix:/run/uwsgi/apivndeveloper.sock;
}

# configuration of the server
server {
	listen		80;
	server_name 	api.vndeveloper.com;
	charset		utf-8;
	# max upload size
	client_max_body_size 75M;
	# Django media & static
	location /media  {
		alias /var/www/apivndeveloper/media;
	}
	location /static {
		alias /var/www/apivndeveloper/static;
	}
	# Finally, send all non-media requests to the Django server.
	location / {
		uwsgi_pass  django;
		include uwsgi_params;
		
		uwsgi_param Host $host;
		uwsgi_param X-Real-IP $remote_addr;
		uwsgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
		uwsgi_param X-Forwarded-Proto $http_x_forwarded_proto;
	}
}" > /etc/nginx/conf.d/apivndeveloper.conf

systemctl start nginx
django-admin.py startproject apivndeveloper

python manage.py runserver 0.0.0.0:8000 
uwsgi --http :8000 --module apivndeveloper.wsgi 

useradd -s /bin/false -r uwsgi

- mkdir -p /etc/uwsgi/vassals

echo -e "[uwsgi]
# Django-related settings
# the base directory (full path)
chdir = /var/www/apivndeveloper
# Django's wsgi file
module =apivndeveloper.wsgi
# the virtualenv (full path)
home = /var/www/p3venv
# Logs
logdate = True
logto = /var/log/uwsgi/access.log
# process-related settings
# master
master = true
# maximum number of worker processes
processes = 5
# the socket (use the full path to be safe)
socket = /run/uwsgi/apivndeveloper.sock
# ... with appropriate permissions - may be needed
chmod-socket = 666
# clear environment on exit
vacuum = true" >> /var/www/apivndeveloper/apivndeveloper_uwsgi.ini

###Quick test if the configuration is good by start uWSGI server and navigate to http://api.vndeveloper.com.###
###You should get “It worked! Congratulations on your first Django-powered page.”###

echo -e "[Unit]
Description=uWSGI Emperor service
[Service]
ExecStartPre=/usr/bin/bash -c 'mkdir -p /run/uwsgi; chown uwsgi:nginx /run/uwsgi'
ExecStart=/var/www/p3venv/bin/uwsgi --emperor /etc/uwsgi/vassals
Restart=always
KillSignal=SIGQUIT
Type=notify
NotifyAccess=all
[Install]
WantedBy=multi-user.target" >> /etc/systemd/system/uwsgi.service

###the path to this file is vi /etc/systemd/system/uwsgi.service###

systemctl stop nginx
systemctl start uwsgi
systemctl start nginx



###FINAL THOUGHTS FROM AUTHOR###
### am still stuck at apivndeveloper_uwsgi.ini with chmod-socket = 666.###
###Whenever I change it to chmod-socket = 664, I get 502 bad gateway.###
###If someone knows the cause and how to fix it, please let me know.###
###BELOW IS THE RESPONSE IN COMMENTS FROM A USER###
###It appears to me that you are accessing your site via uWSGI directly.### 
###If you want to use it (uWSGI), then just change the port from 8000 to 80 or you can serve all requests via nginx (proxy).###
