#!/bin/bash

yum install git -y

git clone https://github.com/passwordlandia/ldap.git

#!/bin/bash

yum install git -y

git clone https://github.com/passwordlandia/ldap.git

gcloud compute instances create ldap-test-b \
    --zone us-east1-b \
    --machine-type f1-micro \
    --image-family centos-7 \
    --image-project centos-cloud \
    --tags "http-server","https-server" \
    --metadata= startup-script-url "https://raw.githubusercontent.com/passwordlandia/ldap/master/startupscriptmaster/ldapstartuplab" \
    
ip=$(gcloud compute instances list | grep ldap-test-b | awk '{ print $4 }' | tail -1) 

echo $ldapip > ldapip.txt

    
ip=$(gcloud compute instances list | grep ldap-test-b | awk '{ print $4 }' | tail -1) 

echo $ldapip > ldapip.txt
