#!/bin/bash

yum -y install google-cloud-sdk
gcloud init

yum -y install python-pip
pip install --upgrade pip
pip install oauth2client
pip install --upgrade google-api-python-client

gcloud compute instances list

yum install git -y
git clone https://github.com/passwordlandia/ldap.git

gcloud compute instances create ldap-test-b \
    --zone us-east1-b \
    --machine-type f1-micro \
    --image-family centos-7 \
    --image-project centos-cloud \
    --tags "http-server","https-server" \
    --metadata-from-file startup-script="passwordlandia/ldap/ldap/StartupScriptMaster/ldap-startup-script.sh" \
    
ip=$(gcloud compute instances list | grep ldap-test-b | awk '{ print $4 }' | tail -1) \

echo $ldapip
