#!/bin/bash

yum install git -y

git clone https://github.com/passwordlandia/ldap.git

gcloud compute instances create ldap-test-b --zone us-east1-b --metadata-from-file startup-script="/ldap/startupscriptmaster/ldapstartupscript.sh"
    
ip=$(gcloud compute instances list | grep ldap-test-b | awk '{ print $4 }' | tail -1) 

echo $ldapip > ldapip.txt
