#!/bin/bash

yum -y install exim mailx

mkdir /root/SSL/mail.mydomain.com -p
cd /root/SSL/mail.mydomain.com
openssl req -nodes -x509 -newkey rsa:2048 -keyout mail.mydomain.com.key -out mail.mydomain.com.crt -days 365
cp mail.mydomain.com.key mail.mydomain.com.crt /etc/ssl/

sed line for inputs

cp /etc/exim/exim.conf{,.orig}

yum -y install wget

####Then wget the exim config file: you can check the contents here:/etc/exim/exim.conf####

wget https://raw.githubusercontent.com/passwordlandia/ldap/master/startupscriptmaster/exim.conf

systemctl start exim
systemctl status exim
systemctl enable exim

yum -y install dovecot

sed -i "ssl = required/ssl = Yes" /g' /etc/dovecot/conf.d/10-ssl.conf
###To test: echo "test" | /usr/sbin/exim -v nicolebade@mydomain.com where nicolebade@mydomain.com is your gcloud user,### 
###you should see exam working to deliver the message. It won't go through because of port blockage,### 
###but you'll be able to see it in the output of your command.###

###if you tail /var/log/exim/main.log you should see the mail attempting to be sent and timing out:###

###Complete this assignment by automating your build of the mail server.###
If you need help, don't hesitate to ask. Note that "wgeting" exim and dovecot config files is fine to complete the configuration.###
