#!/bin/bash

yum -y install google-cloud-sdk
google-cloud-sdk-app-engine-python
gcloud init

yum -y install python-pip
pip install --upgrade pip
pip install oauth2client
pip install --upgrade google-api-python-client

yum install git -y

git clone https://github.com/passwordlandia/ldap.git

####LDAP SERVER START#####
gcloud compute instances create ldap-final-server \
    --zone us-east1-b \
    --machine-type f1-micro \
    --image-family centos-7 \
    --image-project centos-cloud \
    --tags "http-server","https-server" \
    --metadata-from-file startup-script="/ldap/startupscriptmaster/ldapstartupscript.sh"
    
ldapip=$(gcloud compute instances list | grep ldap-final-server | awk '{ print $4 }' | tail -1) 

echo $ldapip > ldapip.txt
####LDAP SERVER END#####

#####NFS SERVER START####
gcloud compute instances create nfs-final-server \
    --zone us-east1-b \
    --machine-type f1-micro \
    --image-family centos-7 \
    --image-project centos-cloud \
    --tags "http-server","https-server" \
    --metadata-from-file startup-script="/ldap/startupscriptmaster/nfsstartupscript.sh"
    
nfsip=$(gcloud compute instances list | grep nfs-final-server | awk '{ print $4 }' | tail -1) 

echo $nfsip > nfsip.txt
#####NFS SERVER END#####

####UBNFS CLIENT A START#####
gcloud compute instances create ldapubnfscl-a-final \
    --zone us-east1-b \
    --machine-type f1-micro \
    --image-family ubuntu-1604-lts \
    --image-project ubuntu-os-cloud \
    --tags "http-server","https-server" \
    --metadata-from-file startup-script="/ldap/startupscriptmaster/ubnfsclientstartupscript.sh"

####UBNFS CLIENT A END#####

####UBNFS CLIENT B START#####
gcloud compute instances create ldapubnfscl-b-final \
    --zone us-east1-b \
    --machine-type f1-micro \
    --image-family ubuntu-1604-lts \
    --image-project ubuntu-os-cloud \
    --tags "http-server","https-server" \
    --metadata-from-file startup-script="/ldap/startupscriptmaster/ubnfsclientstartupscript.sh"

####UBNFS CLIENT B END#####

####POSTGRES SERVER START#####
gcloud compute instances create postgres-final-server\
    --zone us-east1-b \
    --machine-type f1-micro \
    --image-family centos-7 \
    --image-project centos-cloud \
    --tags "http-server","https-server" \
    --metadata-from-file startup-script="/ldap/startupscriptmaster/postgresstartupscript.sh"
    
postgresip=$(gcloud compute instances list | grep postgres-final-server | awk '{ print $4 }' | tail -1) 

echo $postgresip > postgresip.txt
####POSTGRES SERVER END####

####DJANGO SERVER START####
gcloud compute instances create django-final-server \
    --zone us-east1-b \
    --machine-type f1-micro \
    --image-family centos-7 \
    --image-project centos-cloud \
    --tags "http-server","https-server" \
    --metadata-from-file startup-script="/ldap/startupscriptmaster/djangoserverstartupscript.sh"
    
postgresip=$(gcloud compute instances list | grep django-final-server | awk '{ print $4 }' | tail -1) 

echo $djangoip > djangoip.txt
####DJANGO SERVER END####

####MAILSERV#####
gcloud compute instances create mailserv-final \
    --zone us-east1-b \
    --machine-type f1-micro \
    --image-family centos-7 \
    --image-project centos-cloud \
    --tags "http-server","https-server" \
    --metadata-from-file startup-script="/ldap/startupscriptmaster/mailservstartupscript.sh"
    
mailservip=$(gcloud compute instances list | grep mailserv-final | awk '{ print $4 }' | tail -1) 

echo $mailservip > mailservip.txt
####MAILSERV END#####

##END OF SCRIPT####
