#!/bin/bash

yum install -y epel-release
yum update -y
yum install python-pip -y

pip install virtualenv
pip install --upgrade pip
yum install -y telnet

mkdir /opt/myproject
cd /opt/myproject

virtualenv myprojectenv

source myprojectenv/bin/activate
pip install django psycopg2


pip install wget
cd /opt/myproject/myproject

django-admin.py startproject myproject .

curl https://raw.githubusercontent.com/passwordlandia/ldap/master/postgres/settings.py >> settings.py

python manage.py makemigrations
python manage.py migrate

python manage.py runserver 0.0.0.0:8000
